### ISSUE TITLE
Issue with print

### ISSUE THREAD

**Issue by lorddarkangel** [altran-machine-learning-course/course_11_2017_team3#1]
I have an issue with the last lines of the first notebook.
It seems that the print statement is wrong in utils.py! But I can't figure how to solve it, even if it's correct  to change this file...
The error is:
```
  File "../input\utils.py", line 29
    print accuracy_score(test)
                       ^
SyntaxError: invalid syntax
```

**Comment by carlescarmonacalpe** [comment]
Hi!

Depending on your python version the print has different syntax :

In python 2.0 you can use: 
print x
print(x)

In python 3.x only
Print(x)

We didn’t update the notebook (sorry :()) but changing the line to:
Print(accuracy-score(test))

All the things work as expected!

Thank you!!!!!!
