### ISSUE TITLE
No module named 'utils'

### ISSUE THREAD

**Issue by lorddarkangel** [altran-machine-learning-course/course_11_2017_team3#2]
![image](https://user-images.githubusercontent.com/8974974/33528590-74cce7e8-d863-11e7-922b-26499e442904.png)
How can I solve this issue?

**Comment by carlescarmonacalpe** [comment]
Hi!

Seems that you didn't execute the first cell that contains this instruction:
# Add input as import path
sys.path.insert(0,'../input')

If don't work, you can copy the method accuracy_score from input/utils.py and put it in your cell in the jupyter notebook!
